# Generated by Django 3.2 on 2023-05-06 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='username_is_not_me',
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user',
        ),
    ]
